# Generated by Django 4.1.4 on 2022-12-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERACCOUNTS', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
