# Generated by Django 4.1.4 on 2022-12-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('USERACCOUNTS', '0002_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankdata',
            fields=[
                ('bank_name', models.CharField(blank=True, db_column='BANK_NAME', max_length=20, null=True)),
                ('deposit_no', models.IntegerField(db_column='DEPOSIT_NO', primary_key=True, serialize=False)),
                ('deposit_amount', models.IntegerField(blank=True, db_column='DEPOSIT_AMOUNT', null=True)),
                ('maturity_date', models.DateField(blank=True, db_column='MATURITY_DATE', null=True)),
                ('emi_number', models.IntegerField(blank=True, db_column='EMI_NUMBER', null=True)),
                ('emi_amount', models.IntegerField(blank=True, db_column='EMI_AMOUNT', null=True)),
                ('loan_no', models.IntegerField(blank=True, db_column='LOAN_NO', null=True)),
                ('withdrawable_amount', models.IntegerField(blank=True, db_column='WITHDRAWABLE_AMOUNT', null=True)),
                ('total_asset', models.BigIntegerField(blank=True, db_column='TOTAL_ASSET', null=True)),
            ],
            options={
                'db_table': 'bankdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('expense_acronym', models.CharField(db_column='EXPENSE_ACRONYM', max_length=1, primary_key=True, serialize=False)),
                ('expense_category', models.CharField(blank=True, db_column='EXPENSE_CATEGORY', max_length=20, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incomesources',
            fields=[
                ('source_id', models.IntegerField(db_column='SOURCE_ID', primary_key=True, serialize=False)),
                ('monthly_income', models.IntegerField(blank=True, db_column='MONTHLY_INCOME', null=True)),
                ('rental_income', models.IntegerField(blank=True, db_column='RENTAL_INCOME', null=True)),
                ('intrest_amount', models.IntegerField(blank=True, db_column='INTREST_AMOUNT', null=True)),
                ('other_sources', models.IntegerField(blank=True, db_column='OTHER_SOURCES', null=True)),
                ('total_cash', models.IntegerField(blank=True, db_column='TOTAL_CASH', null=True)),
                ('bank_balance', models.BigIntegerField(blank=True, db_column='BANK_BALANCE', null=True)),
                ('net_amount', models.BigIntegerField(blank=True, db_column='NET_AMOUNT', null=True)),
            ],
            options={
                'db_table': 'incomesources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyExpenses',
            fields=[
                ('expense_no', models.IntegerField(db_column='EXPENSE_NO', primary_key=True, serialize=False)),
                ('date_of_expense', models.DateField(blank=True, db_column='DATE_OF_EXPENSE', null=True)),
                ('expense_desc', models.CharField(blank=True, db_column='EXPENSE_DESC', max_length=20, null=True)),
                ('mode_of_payment', models.CharField(blank=True, db_column='MODE_OF_PAYMENT', max_length=20, null=True)),
            ],
            options={
                'db_table': 'monthly_expenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('user_id', models.CharField(db_column='USER_ID', max_length=6, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='USERNAME', max_length=50, null=True)),
                ('gender', models.CharField(blank=True, db_column='GENDER', max_length=1, null=True)),
                ('age', models.IntegerField(blank=True, db_column='AGE', null=True)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=30, null=True)),
                ('phone_no', models.BigIntegerField(blank=True, db_column='PHONE_NO', null=True)),
                ('working_or_not', models.CharField(blank=True, db_column='WORKING_OR_NOT', max_length=2, null=True)),
            ],
            options={
                'db_table': 'userinfo',
                'managed': False,
            },
        ),
    ]
